# Generated by Django 4.1.7 on 2023-02-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceengr',
            old_name='desingnation',
            new_name='designation',
        ),
    ]
